import { ProductSchema, type Product } from "./schema";

const listed = [
  {
    id: "leopard",
    slug: "leopard",
    name: "Leopard",
    searchTerms: ["pink", "brown", "suede", "fringe"],
    category: "knot-bag",
    imageSrc: "/bags/leopard.jpeg",
    sold: false,
  },
  {
    id: "blue-hydrangea",
    slug: "blue-hydrangea",
    name: "Blue hydrangea",
    searchTerms: ["floral", "flower", "white", "suede", "fringe"],
    category: "knot-bag",
    imageSrc: "/bags/blue-hydrangea.jpeg",
    sold: false,
  },
  {
    id: "red-bandana",
    slug: "red-bandana",
    name: "Red bandana",
    searchTerms: ["paisley", "brown", "suede", "fringe"],
    category: "knot-bag",
    imageSrc: "/bags/red-bandana.jpeg",
    sold: false,
  },
  {
    id: "mustard-plaid",
    slug: "mustard-plaid",
    name: "Mustard plaid",
    searchTerms: ["brown", "tan", "suede", "fringe"],
    category: "knot-bag",
    imageSrc: "/bags/mustard-plaid.jpeg",
    sold: false,
  },
  {
    id: "cream-pin-dot",
    slug: "cream-pin-dot",
    name: "Cream pin-dot",
    searchTerms: ["cream", "white", "polka dot", "brown", "suede", "fringe"],
    category: "knot-bag",
    imageSrc: "/bags/cream-pin-dot.jpeg",
    sold: false,
  },
  {
    id: "gold-dot-cream",
    slug: "gold-dot-cream",
    name: "Gold-dot cream",
    searchTerms: ["cream", "white", "yellow", "polka dot", "fringe"],
    category: "knot-bag",
    imageSrc: "/bags/gold-dot-cream.jpeg",
    sold: false,
  },
  {
    id: "rose-toile",
    slug: "rose-toile",
    name: "Rose toile",
    searchTerms: ["pink", "floral", "flower", "cream", "white", "suede", "fringe"],
    category: "knot-bag",
    imageSrc: "/bags/rose-toile.jpeg",
    sold: false,
  },
  {
    id: "dusty-blue-floral",
    slug: "dusty-blue-floral",
    name: "Dusty-blue floral",
    searchTerms: ["pink", "flower", "yellow", "white", "suede", "fringe"],
    category: "knot-bag",
    imageSrc: "/bags/dusty-blue-floral.jpeg",
    sold: false,
  },
  {
    id: "cowhide",
    slug: "cowhide",
    name: "Cowhide",
    price: 75,
    searchTerms: ["cow", "cow print", "black", "brown", "suede", "fringe"],
    category: "knot-bag",
    imageSrc: "/bags/cowhide.jpeg",
    sold: false,
  },
  {
    id: "football",
    slug: "football",
    name: "Football",
    searchTerms: ["brown", "orange", "suede", "fringe"],
    category: "knot-bag",
    imageSrc: "/bags/football.jpeg",
    sold: false,
  },
  {
    id: "white-cow",
    slug: "white-cow",
    name: "White cow",
    price: 75,
    searchTerms: ["cow", "cow print", "cowhide", "brown", "black", "suede", "fringe"],
    category: "knot-bag",
    imageSrc: "/bags/white-cow.jpeg",
    sold: false,
  },
  {
    id: "pink-plaid",
    slug: "pink-plaid",
    name: "Pink plaid",
    searchTerms: ["white", "suede", "fringe"],
    category: "knot-bag",
    imageSrc: "/bags/pink-plaid.jpeg",
    sold: false,
  },
  {
    id: "snake",
    slug: "snake",
    name: "Snake",
    price: 75,
    searchTerms: ["snakeskin", "python", "brown", "black", "cream", "suede", "fringe"],
    category: "knot-bag",
    imageSrc: "/bags/snake.jpeg",
    sold: false,
  },
] as const;

export const products: Product[] = ProductSchema.array().min(1).parse(
  listed.map((product) => {
    const price = "price" in product ? product.price : product.category === "knot-bag" ? 65 : 70;
    return {
      ...product,
      price,
      priceLabel: `$${price}`,
    };
  }),
);
