import { ProductSchema, type Product } from "./schema";

export const products: Product[] = ProductSchema.array().min(1).parse([
  {
    id: "leopard",
    slug: "leopard",
    name: "Leopard",
    imageSrc: "/bags/leopard.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "blue-hydrangea",
    slug: "blue-hydrangea",
    name: "Blue hydrangea",
    imageSrc: "/bags/blue-hydrangea.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "red-bandana",
    slug: "red-bandana",
    name: "Red bandana",
    imageSrc: "/bags/red-bandana.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "mustard-plaid",
    slug: "mustard-plaid",
    name: "Mustard plaid",
    imageSrc: "/bags/mustard-plaid.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "cream-pin-dot",
    slug: "cream-pin-dot",
    name: "Cream pin-dot",
    imageSrc: "/bags/cream-pin-dot.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "gold-dot-cream",
    slug: "gold-dot-cream",
    name: "Gold-dot cream",
    imageSrc: "/bags/gold-dot-cream.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "rose-toile",
    slug: "rose-toile",
    name: "Rose toile",
    imageSrc: "/bags/rose-toile.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "dusty-blue-floral",
    slug: "dusty-blue-floral",
    name: "Dusty-blue floral",
    imageSrc: "/bags/dusty-blue-floral.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
]);
