import { ProductSchema, type Product } from "./schema";

export const products: Product[] = ProductSchema.array().min(1).parse([
  {
    id: "leopard",
    slug: "leopard",
    name: "Leopard",
    category: "knot-bag",
    imageSrc: "/bags/leopard.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "blue-hydrangea",
    slug: "blue-hydrangea",
    name: "Blue hydrangea",
    category: "knot-bag",
    imageSrc: "/bags/blue-hydrangea.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "red-bandana",
    slug: "red-bandana",
    name: "Red bandana",
    category: "knot-bag",
    imageSrc: "/bags/red-bandana.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "mustard-plaid",
    slug: "mustard-plaid",
    name: "Mustard plaid",
    category: "knot-bag",
    imageSrc: "/bags/mustard-plaid.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "cream-pin-dot",
    slug: "cream-pin-dot",
    name: "Cream pin-dot",
    category: "knot-bag",
    imageSrc: "/bags/cream-pin-dot.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "gold-dot-cream",
    slug: "gold-dot-cream",
    name: "Gold-dot cream",
    category: "knot-bag",
    imageSrc: "/bags/gold-dot-cream.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "rose-toile",
    slug: "rose-toile",
    name: "Rose toile",
    category: "knot-bag",
    imageSrc: "/bags/rose-toile.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "dusty-blue-floral",
    slug: "dusty-blue-floral",
    name: "Dusty-blue floral",
    category: "knot-bag",
    imageSrc: "/bags/dusty-blue-floral.jpeg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "pearl-oyster",
    slug: "pearl-oyster",
    name: "Pearl oyster",
    category: "applique-tank",
    imageSrc: "/apparel/pearl-oyster.jpg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "pink-scallop",
    slug: "pink-scallop",
    name: "Pink scallop",
    category: "applique-tank",
    imageSrc: "/apparel/pink-scallop.jpg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "pearl-conch",
    slug: "pearl-conch",
    name: "Pearl conch",
    category: "applique-tank",
    imageSrc: "/apparel/pearl-conch.jpg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "sunflower",
    slug: "sunflower",
    name: "Sunflower",
    category: "applique-tank",
    imageSrc: "/apparel/sunflower.jpg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "lobster",
    slug: "lobster",
    name: "Lobster",
    category: "applique-tank",
    imageSrc: "/apparel/lobster.jpg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "sea-turtle",
    slug: "sea-turtle",
    name: "Sea turtle",
    category: "applique-tank",
    imageSrc: "/apparel/sea-turtle.jpg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "hibiscus",
    slug: "hibiscus",
    name: "Hibiscus",
    category: "applique-tank",
    imageSrc: "/apparel/hibiscus.jpg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "aqua-oyster",
    slug: "aqua-oyster",
    name: "Aqua oyster",
    category: "applique-tank",
    imageSrc: "/apparel/aqua-oyster.jpg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "orange-crab",
    slug: "orange-crab",
    name: "Orange crab",
    category: "applique-tank",
    imageSrc: "/apparel/orange-crab.jpg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "palm-tree",
    slug: "palm-tree",
    name: "Palm tree",
    category: "applique-tank",
    imageSrc: "/apparel/palm-tree.jpg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
  {
    id: "red-crab",
    slug: "red-crab",
    name: "Red crab",
    category: "applique-tank",
    imageSrc: "/apparel/red-crab.jpg",
    priceLabel: "Price on request",
    sold: false,
    tagline: "one of a kind",
  },
]);
